// Code generated by protoc-gen-go. DO NOT EDIT.
// source: AuthenticationService.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserAuthenticationDetails struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserAuthenticationDetails) Reset()         { *m = UserAuthenticationDetails{} }
func (m *UserAuthenticationDetails) String() string { return proto.CompactTextString(m) }
func (*UserAuthenticationDetails) ProtoMessage()    {}
func (*UserAuthenticationDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_b349bfd62d52c6a4, []int{0}
}

func (m *UserAuthenticationDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAuthenticationDetails.Unmarshal(m, b)
}
func (m *UserAuthenticationDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAuthenticationDetails.Marshal(b, m, deterministic)
}
func (m *UserAuthenticationDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAuthenticationDetails.Merge(m, src)
}
func (m *UserAuthenticationDetails) XXX_Size() int {
	return xxx_messageInfo_UserAuthenticationDetails.Size(m)
}
func (m *UserAuthenticationDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAuthenticationDetails.DiscardUnknown(m)
}

var xxx_messageInfo_UserAuthenticationDetails proto.InternalMessageInfo

func (m *UserAuthenticationDetails) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type CreateTokenResult struct {
	IsSuccess            bool     `protobuf:"varint,1,opt,name=isSuccess,proto3" json:"isSuccess,omitempty"`
	StatusCode           int32    `protobuf:"varint,2,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTokenResult) Reset()         { *m = CreateTokenResult{} }
func (m *CreateTokenResult) String() string { return proto.CompactTextString(m) }
func (*CreateTokenResult) ProtoMessage()    {}
func (*CreateTokenResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_b349bfd62d52c6a4, []int{1}
}

func (m *CreateTokenResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTokenResult.Unmarshal(m, b)
}
func (m *CreateTokenResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTokenResult.Marshal(b, m, deterministic)
}
func (m *CreateTokenResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTokenResult.Merge(m, src)
}
func (m *CreateTokenResult) XXX_Size() int {
	return xxx_messageInfo_CreateTokenResult.Size(m)
}
func (m *CreateTokenResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTokenResult.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTokenResult proto.InternalMessageInfo

func (m *CreateTokenResult) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

func (m *CreateTokenResult) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *CreateTokenResult) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Token struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_b349bfd62d52c6a4, []int{2}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ValidateTokenResult struct {
	IsSuccess            bool     `protobuf:"varint,1,opt,name=isSuccess,proto3" json:"isSuccess,omitempty"`
	StatusCode           int32    `protobuf:"varint,2,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateTokenResult) Reset()         { *m = ValidateTokenResult{} }
func (m *ValidateTokenResult) String() string { return proto.CompactTextString(m) }
func (*ValidateTokenResult) ProtoMessage()    {}
func (*ValidateTokenResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_b349bfd62d52c6a4, []int{3}
}

func (m *ValidateTokenResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateTokenResult.Unmarshal(m, b)
}
func (m *ValidateTokenResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateTokenResult.Marshal(b, m, deterministic)
}
func (m *ValidateTokenResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateTokenResult.Merge(m, src)
}
func (m *ValidateTokenResult) XXX_Size() int {
	return xxx_messageInfo_ValidateTokenResult.Size(m)
}
func (m *ValidateTokenResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateTokenResult.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateTokenResult proto.InternalMessageInfo

func (m *ValidateTokenResult) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

func (m *ValidateTokenResult) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func init() {
	proto.RegisterType((*UserAuthenticationDetails)(nil), "proto.UserAuthenticationDetails")
	proto.RegisterType((*CreateTokenResult)(nil), "proto.CreateTokenResult")
	proto.RegisterType((*Token)(nil), "proto.Token")
	proto.RegisterType((*ValidateTokenResult)(nil), "proto.ValidateTokenResult")
}

func init() { proto.RegisterFile("AuthenticationService.proto", fileDescriptor_b349bfd62d52c6a4) }

var fileDescriptor_b349bfd62d52c6a4 = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x50, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x6d, 0x40, 0x41, 0xed, 0x51, 0x06, 0x0e, 0x90, 0x42, 0xf8, 0x50, 0xe4, 0xa9, 0x53, 0x07,
	0x18, 0x40, 0x62, 0x42, 0x65, 0x63, 0x73, 0x80, 0xdd, 0xa4, 0x07, 0xb5, 0x08, 0x31, 0xf2, 0x9d,
	0xf9, 0xb3, 0xfc, 0x19, 0x84, 0x1b, 0xd1, 0x54, 0x04, 0x26, 0x26, 0xeb, 0xdd, 0x7b, 0xe7, 0x77,
	0xef, 0xc1, 0xd1, 0x75, 0x90, 0x05, 0x35, 0x62, 0x2b, 0x23, 0xd6, 0x35, 0x25, 0xf9, 0x77, 0x5b,
	0xd1, 0xf4, 0xcd, 0x3b, 0x71, 0x98, 0xc6, 0x47, 0x5d, 0xc0, 0xe1, 0x3d, 0x93, 0x5f, 0x57, 0xde,
	0x90, 0x18, 0x5b, 0x33, 0xe6, 0x30, 0x0c, 0x4c, 0xbe, 0x31, 0xaf, 0x94, 0x25, 0x45, 0x32, 0x19,
	0xe9, 0x6f, 0xac, 0x9e, 0x61, 0x77, 0xe6, 0xc9, 0x08, 0xdd, 0xb9, 0x17, 0x6a, 0x34, 0x71, 0xa8,
	0x05, 0x8f, 0x61, 0x64, 0xb9, 0x0c, 0x55, 0x45, 0xcc, 0x71, 0x63, 0xa8, 0x57, 0x03, 0x3c, 0x05,
	0x60, 0x31, 0x12, 0x78, 0xe6, 0xe6, 0x94, 0x6d, 0x14, 0xc9, 0x24, 0xd5, 0x9d, 0x09, 0xee, 0x43,
	0x2a, 0x5f, 0x9f, 0x65, 0x9b, 0xd1, 0x6b, 0x09, 0xd4, 0x09, 0xa4, 0xd1, 0x62, 0x45, 0x27, 0x5d,
	0xba, 0x84, 0xbd, 0x07, 0x53, 0xdb, 0xf9, 0x7f, 0x5e, 0x72, 0xf6, 0x91, 0xc0, 0x41, 0x6f, 0x79,
	0x78, 0x0b, 0xdb, 0x9d, 0xd8, 0x58, 0x2c, 0xdb, 0x9c, 0xfe, 0xda, 0x61, 0x9e, 0xb5, 0x8a, 0x1f,
	0x65, 0xa9, 0x01, 0x5e, 0xc1, 0xce, 0xda, 0xed, 0x38, 0x6e, 0xc5, 0x11, 0xe5, 0x79, 0x8b, 0x7a,
	0xf2, 0xa9, 0x01, 0x5e, 0xc2, 0x58, 0xd3, 0x93, 0x27, 0x5e, 0xf4, 0xed, 0xfe, 0x61, 0xfb, 0xb8,
	0x15, 0xa9, 0xf3, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x40, 0x9d, 0x09, 0x53, 0x20, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthenticationServiceClient is the client API for AuthenticationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthenticationServiceClient interface {
	CreateToken(ctx context.Context, in *UserAuthenticationDetails, opts ...grpc.CallOption) (*CreateTokenResult, error)
	ValidateToken(ctx context.Context, in *Token, opts ...grpc.CallOption) (*ValidateTokenResult, error)
	RefreshToken(ctx context.Context, in *Token, opts ...grpc.CallOption) (*CreateTokenResult, error)
}

type authenticationServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthenticationServiceClient(cc *grpc.ClientConn) AuthenticationServiceClient {
	return &authenticationServiceClient{cc}
}

func (c *authenticationServiceClient) CreateToken(ctx context.Context, in *UserAuthenticationDetails, opts ...grpc.CallOption) (*CreateTokenResult, error) {
	out := new(CreateTokenResult)
	err := c.cc.Invoke(ctx, "/proto.AuthenticationService/CreateToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) ValidateToken(ctx context.Context, in *Token, opts ...grpc.CallOption) (*ValidateTokenResult, error) {
	out := new(ValidateTokenResult)
	err := c.cc.Invoke(ctx, "/proto.AuthenticationService/ValidateToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) RefreshToken(ctx context.Context, in *Token, opts ...grpc.CallOption) (*CreateTokenResult, error) {
	out := new(CreateTokenResult)
	err := c.cc.Invoke(ctx, "/proto.AuthenticationService/RefreshToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthenticationServiceServer is the server API for AuthenticationService service.
type AuthenticationServiceServer interface {
	CreateToken(context.Context, *UserAuthenticationDetails) (*CreateTokenResult, error)
	ValidateToken(context.Context, *Token) (*ValidateTokenResult, error)
	RefreshToken(context.Context, *Token) (*CreateTokenResult, error)
}

// UnimplementedAuthenticationServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthenticationServiceServer struct {
}

func (*UnimplementedAuthenticationServiceServer) CreateToken(ctx context.Context, req *UserAuthenticationDetails) (*CreateTokenResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateToken not implemented")
}
func (*UnimplementedAuthenticationServiceServer) ValidateToken(ctx context.Context, req *Token) (*ValidateTokenResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateToken not implemented")
}
func (*UnimplementedAuthenticationServiceServer) RefreshToken(ctx context.Context, req *Token) (*CreateTokenResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshToken not implemented")
}

func RegisterAuthenticationServiceServer(s *grpc.Server, srv AuthenticationServiceServer) {
	s.RegisterService(&_AuthenticationService_serviceDesc, srv)
}

func _AuthenticationService_CreateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserAuthenticationDetails)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).CreateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AuthenticationService/CreateToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).CreateToken(ctx, req.(*UserAuthenticationDetails))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_ValidateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Token)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).ValidateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AuthenticationService/ValidateToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).ValidateToken(ctx, req.(*Token))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Token)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AuthenticationService/RefreshToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).RefreshToken(ctx, req.(*Token))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthenticationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AuthenticationService",
	HandlerType: (*AuthenticationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateToken",
			Handler:    _AuthenticationService_CreateToken_Handler,
		},
		{
			MethodName: "ValidateToken",
			Handler:    _AuthenticationService_ValidateToken_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _AuthenticationService_RefreshToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "AuthenticationService.proto",
}
