// Code generated by protoc-gen-go. DO NOT EDIT.
// source: AuthenticationService.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ClaimsDetails struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClaimsDetails) Reset()         { *m = ClaimsDetails{} }
func (m *ClaimsDetails) String() string { return proto.CompactTextString(m) }
func (*ClaimsDetails) ProtoMessage()    {}
func (*ClaimsDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_b349bfd62d52c6a4, []int{0}
}

func (m *ClaimsDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClaimsDetails.Unmarshal(m, b)
}
func (m *ClaimsDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClaimsDetails.Marshal(b, m, deterministic)
}
func (m *ClaimsDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClaimsDetails.Merge(m, src)
}
func (m *ClaimsDetails) XXX_Size() int {
	return xxx_messageInfo_ClaimsDetails.Size(m)
}
func (m *ClaimsDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_ClaimsDetails.DiscardUnknown(m)
}

var xxx_messageInfo_ClaimsDetails proto.InternalMessageInfo

func (m *ClaimsDetails) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type TokenResult struct {
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenResult) Reset()         { *m = TokenResult{} }
func (m *TokenResult) String() string { return proto.CompactTextString(m) }
func (*TokenResult) ProtoMessage()    {}
func (*TokenResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_b349bfd62d52c6a4, []int{1}
}

func (m *TokenResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenResult.Unmarshal(m, b)
}
func (m *TokenResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenResult.Marshal(b, m, deterministic)
}
func (m *TokenResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenResult.Merge(m, src)
}
func (m *TokenResult) XXX_Size() int {
	return xxx_messageInfo_TokenResult.Size(m)
}
func (m *TokenResult) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenResult.DiscardUnknown(m)
}

var xxx_messageInfo_TokenResult proto.InternalMessageInfo

func (m *TokenResult) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Token struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_b349bfd62d52c6a4, []int{2}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ValidateTokenResult struct {
	IsValid              bool     `protobuf:"varint,1,opt,name=isValid,proto3" json:"isValid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateTokenResult) Reset()         { *m = ValidateTokenResult{} }
func (m *ValidateTokenResult) String() string { return proto.CompactTextString(m) }
func (*ValidateTokenResult) ProtoMessage()    {}
func (*ValidateTokenResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_b349bfd62d52c6a4, []int{3}
}

func (m *ValidateTokenResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateTokenResult.Unmarshal(m, b)
}
func (m *ValidateTokenResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateTokenResult.Marshal(b, m, deterministic)
}
func (m *ValidateTokenResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateTokenResult.Merge(m, src)
}
func (m *ValidateTokenResult) XXX_Size() int {
	return xxx_messageInfo_ValidateTokenResult.Size(m)
}
func (m *ValidateTokenResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateTokenResult.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateTokenResult proto.InternalMessageInfo

func (m *ValidateTokenResult) GetIsValid() bool {
	if m != nil {
		return m.IsValid
	}
	return false
}

func init() {
	proto.RegisterType((*ClaimsDetails)(nil), "proto.ClaimsDetails")
	proto.RegisterType((*TokenResult)(nil), "proto.TokenResult")
	proto.RegisterType((*Token)(nil), "proto.Token")
	proto.RegisterType((*ValidateTokenResult)(nil), "proto.ValidateTokenResult")
}

func init() { proto.RegisterFile("AuthenticationService.proto", fileDescriptor_b349bfd62d52c6a4) }

var fileDescriptor_b349bfd62d52c6a4 = []byte{
	// 228 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0x1b, 0x64, 0xb5, 0x4e, 0xdb, 0xcb, 0x58, 0x61, 0x89, 0x08, 0x12, 0x2f, 0x82, 0x50,
	0xa1, 0x9e, 0xc4, 0x93, 0xd4, 0x5f, 0x10, 0xc5, 0x7b, 0xac, 0x23, 0x0d, 0xa6, 0x89, 0x24, 0xb3,
	0xfe, 0x41, 0xff, 0x98, 0x98, 0x76, 0x35, 0x0b, 0x39, 0x85, 0x6f, 0xde, 0xcb, 0xcc, 0x7b, 0x70,
	0xf6, 0xd0, 0xf1, 0x86, 0x3c, 0xdb, 0xb5, 0x61, 0x1b, 0xfc, 0x13, 0xc5, 0x2f, 0xbb, 0xa6, 0xc5,
	0x67, 0x0c, 0x1c, 0xb0, 0xc9, 0x8f, 0xba, 0x86, 0xd9, 0xca, 0x19, 0xbb, 0x4d, 0x8f, 0xc4, 0xc6,
	0xba, 0x84, 0x12, 0xc6, 0x5d, 0xa2, 0xe8, 0xcd, 0x96, 0x5a, 0x71, 0x21, 0xae, 0x8e, 0xf5, 0x1f,
	0xab, 0x4b, 0x98, 0x3c, 0x87, 0x0f, 0xf2, 0x9a, 0x52, 0xe7, 0x18, 0xe7, 0xd0, 0xf0, 0x2f, 0xb6,
	0x07, 0xd9, 0xb7, 0x03, 0x75, 0x0e, 0x4d, 0x36, 0xfd, 0xcb, 0xa2, 0x94, 0x6f, 0xe0, 0xe4, 0xc5,
	0x38, 0xfb, 0x66, 0x98, 0xca, 0x5d, 0x2d, 0x1c, 0xd9, 0x94, 0x85, 0x6c, 0x1f, 0xeb, 0x1e, 0x97,
	0xdf, 0x02, 0x4e, 0xab, 0x45, 0xf0, 0x0e, 0x26, 0xab, 0x48, 0xfd, 0x22, 0x9c, 0xef, 0x9a, 0x2d,
	0x06, 0x7d, 0x24, 0xee, 0xa7, 0xc5, 0x31, 0x35, 0xc2, 0x7b, 0x98, 0x0d, 0x52, 0xe0, 0xb4, 0xb4,
	0x49, 0xb9, 0xa7, 0x4a, 0x52, 0x35, 0xc2, 0x25, 0x4c, 0x35, 0xbd, 0x47, 0x4a, 0x9b, 0xda, 0xdf,
	0xea, 0xc1, 0xd7, 0xc3, 0x3c, 0xbc, 0xfd, 0x09, 0x00, 0x00, 0xff, 0xff, 0x93, 0x0b, 0x3d, 0x5a,
	0x94, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthenticationServiceClient is the client API for AuthenticationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthenticationServiceClient interface {
	CreateToken(ctx context.Context, in *ClaimsDetails, opts ...grpc.CallOption) (*TokenResult, error)
	ValidateToken(ctx context.Context, in *Token, opts ...grpc.CallOption) (*ValidateTokenResult, error)
	RefreshToken(ctx context.Context, in *Token, opts ...grpc.CallOption) (*TokenResult, error)
}

type authenticationServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthenticationServiceClient(cc *grpc.ClientConn) AuthenticationServiceClient {
	return &authenticationServiceClient{cc}
}

func (c *authenticationServiceClient) CreateToken(ctx context.Context, in *ClaimsDetails, opts ...grpc.CallOption) (*TokenResult, error) {
	out := new(TokenResult)
	err := c.cc.Invoke(ctx, "/proto.AuthenticationService/CreateToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) ValidateToken(ctx context.Context, in *Token, opts ...grpc.CallOption) (*ValidateTokenResult, error) {
	out := new(ValidateTokenResult)
	err := c.cc.Invoke(ctx, "/proto.AuthenticationService/ValidateToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) RefreshToken(ctx context.Context, in *Token, opts ...grpc.CallOption) (*TokenResult, error) {
	out := new(TokenResult)
	err := c.cc.Invoke(ctx, "/proto.AuthenticationService/RefreshToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthenticationServiceServer is the server API for AuthenticationService service.
type AuthenticationServiceServer interface {
	CreateToken(context.Context, *ClaimsDetails) (*TokenResult, error)
	ValidateToken(context.Context, *Token) (*ValidateTokenResult, error)
	RefreshToken(context.Context, *Token) (*TokenResult, error)
}

// UnimplementedAuthenticationServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthenticationServiceServer struct {
}

func (*UnimplementedAuthenticationServiceServer) CreateToken(ctx context.Context, req *ClaimsDetails) (*TokenResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateToken not implemented")
}
func (*UnimplementedAuthenticationServiceServer) ValidateToken(ctx context.Context, req *Token) (*ValidateTokenResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateToken not implemented")
}
func (*UnimplementedAuthenticationServiceServer) RefreshToken(ctx context.Context, req *Token) (*TokenResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshToken not implemented")
}

func RegisterAuthenticationServiceServer(s *grpc.Server, srv AuthenticationServiceServer) {
	s.RegisterService(&_AuthenticationService_serviceDesc, srv)
}

func _AuthenticationService_CreateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimsDetails)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).CreateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AuthenticationService/CreateToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).CreateToken(ctx, req.(*ClaimsDetails))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_ValidateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Token)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).ValidateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AuthenticationService/ValidateToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).ValidateToken(ctx, req.(*Token))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Token)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AuthenticationService/RefreshToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).RefreshToken(ctx, req.(*Token))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthenticationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AuthenticationService",
	HandlerType: (*AuthenticationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateToken",
			Handler:    _AuthenticationService_CreateToken_Handler,
		},
		{
			MethodName: "ValidateToken",
			Handler:    _AuthenticationService_ValidateToken_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _AuthenticationService_RefreshToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "AuthenticationService.proto",
}
